// Auto-generated from the approved question set. Do not hand-edit — regenerate from source data instead.
const LIKERT_OPTIONS = [
  "Very Inaccurate",
  "Moderately Inaccurate",
  "Neither Accurate Nor Inaccurate",
  "Moderately Accurate",
  "Very Accurate"
];

const QUESTIONS = [
  "Worry about things.",
  "Make friends easily.",
  "Have a vivid imagination.",
  "Trust others.",
  "Complete tasks successfully.",
  "Get angry easily.",
  "Love large parties.",
  "Believe in the importance of art.",
  "Would never cheat on my taxes.",
  "Like order.",
  "Often feel blue.",
  "Take charge.",
  "Experience my emotions intensely.",
  "Make people feel welcome.",
  "Try to follow the rules.",
  "Am easily intimidated.",
  "Am always busy.",
  "Prefer variety to routine.",
  "Am easy to satisfy.",
  "Go straight for the goal.",
  "Often eat too much.",
  "Love excitement.",
  "Like to solve complex problems.",
  "Dislike being the center of attention.",
  "Get chores done right away.",
  "Panic easily.",
  "Radiate joy.",
  "Tend to vote for liberal political candidates.",
  "Sympathize with the homeless.",
  "Avoid mistakes.",
  "Fear for the worst.",
  "Warm up quickly to others.",
  "Enjoy wild flights of fantasy.",
  "Believe that others have good intentions.",
  "Excel in what I do.",
  "Get irritated easily.",
  "Talk to a lot of different people at parties.",
  "Like music.",
  "Stick to the rules.",
  "Like to tidy up.",
  "Dislike myself.",
  "Try to lead others.",
  "Feel others' emotions.",
  "Anticipate the needs of others.",
  "Keep my promises.",
  "Am afraid that I will do the wrong thing.",
  "Am always on the go.",
  "Like to visit new places.",
  "Can't stand confrontations.",
  "Work hard.",
  "Don't know why I do some of the things I do.",
  "Seek adventure.",
  "Love to read challenging material.",
  "Dislike talking about myself.",
  "Am always prepared.",
  "Become overwhelmed by events.",
  "Have a lot of fun.",
  "Believe that there is no absolute right and wrong.",
  "Feel sympathy for those who are worse off than myself.",
  "Choose my words with care.",
  "Am afraid of many things.",
  "Feel comfortable around people.",
  "Love to daydream.",
  "Trust what people say.",
  "Handle tasks smoothly.",
  "Get upset easily.",
  "Enjoy being part of a group.",
  "See beauty in things that others might not notice.",
  "Use flattery to get ahead.",
  "Want everything to be \"just right.\"",
  "Am often down in the dumps.",
  "Can talk others into doing things.",
  "Am passionate about causes.",
  "Love to help others.",
  "Pay my bills on time.",
  "Find it difficult to approach others.",
  "Do a lot in my spare time.",
  "Am interested in many things.",
  "Hate to seem pushy.",
  "Turn plans into actions.",
  "Do things I later regret.",
  "Love action.",
  "Have a rich vocabulary.",
  "Consider myself an average person.",
  "Start tasks right away.",
  "Feel that I'm unable to deal with things.",
  "Express childlike joy.",
  "Believe that criminals should receive help rather than punishment.",
  "Value cooperation over competition.",
  "Stick to my chosen path.",
  "Get stressed out easily.",
  "Act comfortably with others.",
  "Like to get lost in thought.",
  "Believe that people are basically moral.",
  "Am sure of my ground.",
  "Am often in a bad mood.",
  "Involve others in what I am doing.",
  "Love flowers.",
  "Use others for my own ends.",
  "Love order and regularity.",
  "Have a low opinion of myself.",
  "Seek to influence others.",
  "Enjoy examining myself and my life.",
  "Am concerned about others.",
  "Tell the truth.",
  "Am afraid to draw attention to myself.",
  "Can manage many things at the same time.",
  "Like to begin new things.",
  "Have a sharp tongue.",
  "Plunge into tasks with all my heart.",
  "Go on binges.",
  "Enjoy being part of a loud crowd.",
  "Can handle a lot of information.",
  "Seldom toot my own horn.",
  "Get to work at once.",
  "Can't make up my mind.",
  "Laugh my way through life.",
  "Believe in one true religion.",
  "Suffer from others' sorrows.",
  "Jump into things without thinking.",
  "Get caught up in my problems.",
  "Cheer people up.",
  "Indulge in my fantasies.",
  "Believe in human goodness.",
  "Come up with good solutions.",
  "Lose my temper.",
  "Love surprise parties.",
  "Enjoy the beauty of nature.",
  "Know how to get around the rules.",
  "Do things according to a plan.",
  "Have frequent mood swings.",
  "Take control of things.",
  "Try to understand myself.",
  "Have a good word for everyone.",
  "Listen to my conscience.",
  "Only feel comfortable with friends.",
  "React quickly.",
  "Prefer to stick with things that I know.",
  "Contradict others.",
  "Do more than what's expected of me.",
  "Love to eat.",
  "Enjoy being reckless.",
  "Enjoy thinking about things.",
  "Believe that I am better than others.",
  "Carry out my plans.",
  "Get overwhelmed by emotions.",
  "Love life.",
  "Tend to vote for conservative political candidates.",
  "Am not interested in other people's problems.",
  "Make rash decisions.",
  "Am not easily bothered by things.",
  "Am hard to get to know.",
  "Spend time reflecting on things.",
  "Think that all will be well.",
  "Know how to get things done.",
  "Rarely get irritated.",
  "Prefer to be alone.",
  "Do not like art.",
  "Cheat to get ahead.",
  "Often forget to put things back in their proper place.",
  "Feel desperate.",
  "Wait for others to lead the way.",
  "Seldom get emotional.",
  "Look down on others.",
  "Break rules.",
  "Stumble over my words.",
  "Like to take it easy.",
  "Dislike changes.",
  "Love a good fight.",
  "Set high standards for myself and others.",
  "Rarely overindulge.",
  "Act wild and crazy.",
  "Am not interested in abstract ideas.",
  "Think highly of myself.",
  "Find it difficult to get down to work.",
  "Remain calm under pressure.",
  "Look at the bright side of life.",
  "Believe that too much tax money goes to support artists.",
  "Tend to dislike soft-hearted people.",
  "Like to act on a whim.",
  "Am relaxed most of the time.",
  "Often feel uncomfortable around others.",
  "Seldom daydream.",
  "Distrust people.",
  "Misjudge situations.",
  "Seldom get mad.",
  "Want to be left alone.",
  "Do not like poetry.",
  "Put people under pressure.",
  "Leave a mess in my room.",
  "Feel that my life lacks direction.",
  "Keep in the background.",
  "Am not easily affected by my emotions.",
  "Am indifferent to the feelings of others.",
  "Break my promises.",
  "Am not embarrassed easily.",
  "Like to take my time.",
  "Don't like the idea of change.",
  "Yell at people.",
  "Demand quality.",
  "Easily resist temptations.",
  "Am willing to try anything once.",
  "Avoid philosophical discussions.",
  "Have a high opinion of myself.",
  "Waste my time.",
  "Can handle complex problems.",
  "Laugh aloud.",
  "Believe laws should be strictly enforced.",
  "Believe in an eye for an eye.",
  "Rush into things.",
  "Am not easily disturbed by events.",
  "Avoid contacts with others.",
  "Do not have a good imagination.",
  "Suspect hidden motives in others.",
  "Don't understand things.",
  "Am not easily annoyed.",
  "Don't like crowded events.",
  "Do not enjoy going to art museums.",
  "Pretend to be concerned for others.",
  "Leave my belongings around.",
  "Seldom feel blue.",
  "Have little to say.",
  "Rarely notice my emotional reactions.",
  "Make people feel uncomfortable.",
  "Get others to do my duties.",
  "Am comfortable in unfamiliar situations.",
  "Like a leisurely lifestyle.",
  "Am a creature of habit.",
  "Insult people.",
  "Am not highly motivated to succeed.",
  "Am able to control my cravings.",
  "Seek danger.",
  "Have difficulty understanding abstract ideas.",
  "Know the answers to many questions.",
  "Need a push to get started.",
  "Know how to cope.",
  "Amuse my friends.",
  "Believe that we coddle criminals too much.",
  "Try not to think about the needy.",
  "Do crazy things.",
  "Don't worry about things that have already happened.",
  "Am not really interested in others.",
  "Seldom get lost in thought.",
  "Am wary of others.",
  "Have little to contribute.",
  "Keep my cool.",
  "Avoid crowds.",
  "Do not like concerts.",
  "Take advantage of others.",
  "Am not bothered by messy people.",
  "Feel comfortable with myself.",
  "Don't like to draw attention to myself.",
  "Experience very few emotional highs and lows.",
  "Turn my back on others.",
  "Do the opposite of what is asked.",
  "Am not bothered by difficult social situations.",
  "Let things proceed at their own pace.",
  "Dislike new foods.",
  "Get back at others.",
  "Do just enough work to get by.",
  "Never spend more than I can afford.",
  "Would never go hang gliding or bungee jumping.",
  "Am not interested in theoretical discussions.",
  "Boast about my virtues.",
  "Have difficulty starting tasks.",
  "Readily overcome setbacks.",
  "Am not easily amused.",
  "Believe that we should be tough on crime.",
  "Believe people should fend for themselves.",
  "Act without thinking.",
  "Adapt easily to new situations.",
  "Keep others at a distance.",
  "Have difficulty imagining things.",
  "Believe that people are essentially evil.",
  "Don't see the consequences of things.",
  "Rarely complain.",
  "Seek quiet.",
  "Do not enjoy watching dance performances.",
  "Obstruct others' plans.",
  "Am not bothered by disorder.",
  "Am very pleased with myself.",
  "Hold back my opinions.",
  "Don't understand people who get emotional.",
  "Take no time for others.",
  "Misrepresent the facts.",
  "Am able to stand up for myself.",
  "React slowly.",
  "Am attached to conventional ways.",
  "Hold a grudge.",
  "Put little time and effort into my work.",
  "Never splurge.",
  "Dislike loud music.",
  "Avoid difficult reading material.",
  "Make myself the center of attention.",
  "Postpone decisions.",
  "Am calm even in tense situations.",
  "Seldom joke around.",
  "Like to stand during the national anthem.",
  "Can't stand weak people.",
  "Often make last-minute plans."
];
